### ISSUE TITLE
Use Text instead of String

### ISSUE THREAD

**Issue by patrickt** [tree-sitter/haskell-tree-sitter#105]
We get a Text out of Aeson anyway, there’s no reason to unpack it and do all the operations on Strings.

**Comment by robrix** [comment]
On the other hand, TH uses `String` and not `Text`, so we’re going to have to unpack it eventually anyway, right?

**Comment by patrickt** [comment]
That is true. I’m in favor of avoiding format conversions until the last minute possible (i.e. calling `Text.unpack` at TH-sites rather than early on), but it’s @aymannadeem’s call!

**Comment by patrickt** [comment]
I don’t think this is hugely important in the grand scheme of things.
