### ISSUE TITLE
Every name we’ve come up with for building ASTs from parse trees is terrible

### ISSUE THREAD

**Issue by robrix** [tree-sitter/haskell-tree-sitter#113]
In `semantic` we call this `Assignment` (and once upon a time, “term assignment”), in this repo we’ve called it both `Importing` and `Building` (cf #144), and all of these names are awful.

Please, someone come up with a better name so that we don’t get stuck with this for a further two plus years.

**Comment by patrickt** [comment]
Thoughts: `Assemble`, `Construct`, `Reify`, `Grow`. Or maybe `Lumberjack`/`Carpenter`, since it cuts down trees and assembles richer structures.

**Comment by robrix** [comment]
`Copy`, `Deserialize`, `ParseParseTree`, `Ingest`

**Comment by robrix** [comment]
`Marshal` is reasonably standard for FFI-crossing stuff like this.

Or maybe we should just pretend that parsing and this are a single step, and call it such?

**Comment by domenkozar** [comment]
Why not just call it `AST`? Or maybe `GAST` as Generalized :)

**Comment by robrix** [comment]
@domenkozar Fair, I’ve had tunnel vision on this and focused solely on verbs.

**Comment by robrix** [comment]
This was fixed in #144.
