### ISSUE TITLE
Parse errors aren’t represented in AST datatypes

### ISSUE THREAD

**Issue by robrix** [tree-sitter/haskell-tree-sitter#114]
`tree-sitter` can return parse errors in the tree, but we can’t represent those in the TH-generated AST datatypes.

cc @maxbrunsfeld for context on where parse error nodes can actually be produced (literally anywhere a node can be? or some subset of valid node positions?)

**Comment by robrix** [comment]
This seems slightly related to comments (cf #99).

**Comment by domenkozar** [comment]
I've seen that `Grammar` does generate ParseError, but for Nix I get:

```
canonix: toEnum{Grammar}: tag (65535) is outside of enumeration's range (0,98)
CallStack (from HasCallStack):
  error, called at ./TreeSitter/Nix.hs:15:1 in tree-sitter-nix-0.1.0-AcUfetAdPzz7lGcBxdaPNc:TreeSitter.Nix
```

**Comment by robrix** [comment]
@domenkozar: That’s quite a different bug; the AST datatypes are those being matched against in #144, whereas that `toEnum{Grammar}` thing is coming from the fact that `tree-sitter` represents parse errors as symbol 65535 rather than the # of valid symbols + 1.

Filed as #145.

**Comment by robrix** [comment]
Also related to #263 in that higher-kinded data would support `Either (…error…)` as a viable representation for errors in subterm positions.

**Comment by patrickt** [comment]
@robrix I think that observation is extremely cogent: it shows that #263 is a good idea on multiple fronts.
