### ISSUE TITLE
Publish to hackage/stackage

### ISSUE THREAD

**Issue by Neppord** [tree-sitter/haskell-tree-sitter#124]
Tree sitter would be awesome to use in Haskell scripts using stack. To make this work it needs to be published on stackage.

Also Semantic would be easier to move to stackage if tree sitter already would be there.

Looking forward to be able to use your amazing project in my daily work.

**Comment by patrickt** [comment]
We plan to get this done this week.

**Comment by patrickt** [comment]
@Neppord Just a heads up: this particular package is not yet ready for prime-time, so I wouldn’t recommend building anything atop it unless you’re willing to tolerate a certain level of breakage.

**Comment by patrickt** [comment]
https://hackage.haskell.org/package/tree-sitter

Language packages coming soon.

**Comment by Neppord** [comment]
Awesome! Thanks!

**Comment by patrickt** [comment]
@Neppord All the language packages are up on Hackage. You may need a `cabal new-update hackage.haskell.org,HEAD`

**Comment by Neppord** [comment]
@patrickt When, if, will they be reachable from stackage, do you think?

**Comment by Neppord** [comment]
I found a issue with at least one of the packages see issue #132

But I'm very happy with your work!

**Comment by patrickt** [comment]
@Neppord I don’t have the spare cycles to wrangle those ten separate packages into Stackage. If you (or anyone else) want to take care of curation, I wouldn’t mind, but for both time and simplicity purposes I’m content with having them live on Hackage/in people’s extra-deps stanzas.

**Comment by Neppord** [comment]
Thanks! I'll consider it! :)
