### ISSUE TITLE
Leaf datatypes for constant rules have contents

### ISSUE THREAD

**Issue by robrix** [tree-sitter/haskell-tree-sitter#136]
In Python, `true` and `false` are matched by rules of the same name. The TH generates leaf datatypes for these containing `Text`, like so:

```haskell
newtype True = True { bytes :: Text }
```

However, as there’s no way for the grammar to ever produce a parse tree for which `bytes` is something other than `"true"`, this is superfluous and could be elided for improved performance and a closer match to the language’s semantics. Otherwise put, all values of `True` should really be the same, but the `Text` field means that the datatype doesn’t enforce that.

By contrast, something like `Identifier` really _does_ require the `Text` field, because different `Identifier`s can (and often will) have different contents.

cf #93 which was about adding the `Text` field

cc @maxbrunsfeld for ideas about how to differentiate between the `true`/`false` and `identifier` cases (those for which the contents are static vs. those for which they can vary)

**Comment by patrickt** [comment]
Seems like we should add another field to the JSON output that is `true` iff the bytes contents are the same for any match.

**Comment by maxbrunsfeld** [comment]
There's quite a few rules for which the bytes are *not* fixed. Do we want to make a copy of the text for all strings and comments? It seems like it might entail a lot of potentially-unnecessary copying.

I would think that we'd just want to store the byte offsets on leaf nodes, so that the downstream analysis could choose the nodes for which to examine the text. That way we could avoid any string copying.

**Comment by robrix** [comment]
> There's quite a few rules for which the bytes are _not_ fixed. Do we want to make a copy of the text for all strings and comments? It seems like it might entail a lot of potentially-unnecessary copying.
> 
> I would think that we'd just want to store the byte offsets on leaf nodes, so that the downstream analysis could choose the nodes for which to examine the text. That way we could avoid any string copying.

This is true. However:

- It comes at the expense of having to keep the entirety of the source around forever.
- On the other hand, if we don’t mind the memory cost, `ByteString` can slice without copying, and `Text` _might_ be able to do the same (tho I’d be very surprised if that would survive our current `ByteString` -> `Text` decoding).
- Having to look up source makes every operation downstream _much_ more complicated, since even things like identifiers would have to be looked up every time we need to do any operation.
- We’re going to end up copying all of these anyway to show them, which we will basically always do.
- Every downstream operation would also have to do its own decoding anew, and thus handle the possibility of failure, and most of these operations are not in a good place to do that.
- Equality checks would be essentially meaningless, which would add an extra layer of complication to diffing in particular since it uses equality to short-circuit deeper comparison. Plus it would be extremely surprising to someone using the `Eq` instance to learn that it’s essentially worthless. And it would be a _huge_ pain in the ass to try to keep AST in any kind of set or map due to these operating via typeclasses whose signatures do not admit these kinds of lookup (without egregious or inconvenient hacks).
- It would introduce the potential for getting the originating file out of sync, which in my experience is an extremely easy thing to get wrong.

IMO we _absolutely_ want to copy potentially-varying leaf contents. We just don’t want to copy the ones which are always constant.

**Comment by maxbrunsfeld** [comment]
We can definitely remove the `text` field from nodes where `named` is false (e.g. "+", "-", "===", etc), because those correspond to string literals in the grammar.

Aside from these, there aren't too many nodes whose content doesn't vary. `True`, `False`, `None` etc are among the few. I think that if we're already ok with copying things like strings and comments, which can be arbitrarily large, then copying the occasional `true` shouldn't have a major impact.

> `ByteString` can slice without copying

Yeah, the [docs](http://hackage.haskell.org/package/bytestring-0.10.8.2/docs/Data-ByteString.html#g:13) make it seem like they can:

>  for all splitting functions in this library, this function does not copy the substrings, it just constructs new ByteStrings that are slices of the original.

This seems like a nice property. For the purposes of equality, hashing, etc, it behaves like an owned string, but it doesn't entail any copying.

**Comment by robrix** [comment]
> We can definitely remove the `text` field from nodes where `named` is false (e.g. "+", "-", "===", etc), because those correspond to string literals in the grammar.

Awesome 👍

> I think that if we're already ok with copying things like strings and comments, which can be arbitrarily large, then copying the occasional `true` shouldn't have a major impact.

I’m slightly less bothered by that than by the fact that they’re semantically bogus; it implies that you can have more than one value of `True`. That said, `ghc` does a lot to optimize single-constructor, zero-field datatypes, so there could be some wins there as well.

**Comment by robrix** [comment]
It occurs to me that we could change this in the grammar without affecting the generation of the `node-types.json` file by changing the rule in e.g. the Python grammar from:

```js
{…, true: $ => 'True' }
```

to something more like

```js
{…, true: $ => field('blah', 'True') }
```

which would (I think?) give us a unary field. We could further detect that in the grammar and prune unary fields from products, leaving us with just the annotation:

```haskell
newtype True a = True { ann :: a }
```
