### ISSUE TITLE
Add tree-sitter-rust package.

### ISSUE THREAD

**Issue by patrickt** [tree-sitter/haskell-tree-sitter#137]
https://github.com/tree-sitter/tree-sitter-rust is reasonably complete and usable in Atom. There’s no reason not to bring up the package.

**Comment by XVilka** [comment]
Could be closed, I suppose? https://github.com/tree-sitter/haskell-tree-sitter/tree/master/tree-sitter-rust

**Comment by joshvera** [comment]
yep!
