### ISSUE TITLE
Anonymous nodes generated from tree-sitter grammars should use a single `Token` type

### ISSUE THREAD

**Issue by patrickt** [tree-sitter/haskell-tree-sitter#139]
Right now, for the literal parsed token `def`, we generate an `AnonymousDef` type; for the literal token `=`, we generate an `AnonymousComma` type, etc. We can do this in a smarter way by attaching the parsed string to a single `Token` type, reifying that string as a type-level symbol:

```
data Token (str :: Symbol) = Token
```

Then we can deal in values of `Token @“def”`, `@ @“=“`, etc. Nicer.

**Comment by robrix** [comment]
One advantage of this is that it would mean we don’t have to translate symbols into valid Haskell identifier ✨
