### ISSUE TITLE
consolidate code paths that convert strings to CamelCase

### ISSUE THREAD

**Issue by aymannadeem** [tree-sitter/haskell-tree-sitter#141]
This project contains a number of ways to process a string like `if_statement` to its camel-cased version, `IfStatement`. This is due to code evolving without the upkeep to consolidate shared logic.

Specifically, `toSymbolName`, `toName` and `toName'` should all potentially be one function, somewhere in the future. Not urgent.

**Comment by patrickt** [comment]
This is fixed with #153.
