### ISSUE TITLE
Nested Eithers are annoying to pattern match against

### ISSUE THREAD

**Issue by robrix** [tree-sitter/haskell-tree-sitter#142]
We currently generate fields consisting of nested `Either`s for `choice`s occurring nested in a product type, e.g. for binary operators. This works well enough, but the nesting makes pattern matching kind of tedious and hard to read:

```haskell
param (Left Py.AnonymousComma{}) = fail "lol what"
param (Right (Left Py.DefaultParameter{..})) = fail "lol what"
param (Right (Right (Left Py.DictionarySplat{..}))) = fail "lol what"
param (Right (Right (Right (Left (Py.Identifier name))))) = pure (User name)
param (Right (Right (Right (Right (Left Py.KeywordIdentifier{..}))))) = fail "lol what"
param (Right (Right (Right (Right (Right (Left Py.ListSplat{..})))))) = fail "lol what"
param (Right (Right (Right (Right (Right (Right (Left Py.Tuple{..}))))))) = fail "lol what"
param (Right (Right (Right (Right (Right (Right (Right (Left Py.TypedDefaultParameter{..})))))))) = fail "lol what"
param (Right (Right (Right (Right (Right (Right (Right (Right Py.TypedParameter{..})))))))) = fail "lol what"
```

We might instead be able to use an n-ary sum type which provides flat pattern matching. E.g. [`compound-types`](https://github.com/nikita-volkov/compound-types) (🎩 @patrickt).

**Comment by robrix** [comment]
Mind you, it looks like if we wanted to use that lib, we’d likely have to extend it to higher arities, since it seems to tap out at 7:

https://github.com/nikita-volkov/compound-types/blob/master/library/CompoundTypes/Private/Lazy/Sum.hs#L20-L21

**Comment by robrix** [comment]
@aymannadeem ameliorated this quite a bit in #214 (using `:+:` to represent these sums instead of `Either`) and #225 (arranging them as a balanced binary tree, reducing the maximum depth significantly).

This is a _lot_ better now, especially using some abstraction over the shape of the sum-tree to project out specific structures, but I’m going to leave this open for the time being since we might want to revisit other approaches in future.

**Comment by aymannadeem** [comment]
No rush, but when you get a chance do you mind listing off some thoughts on why we'd revisit/consider different approaches @robrix?

**Comment by robrix** [comment]
Well, nested sums are still annoying to pattern match against.

**Comment by robrix** [comment]
Further, it’s possible that we could find a representation with O(1) injection/projection as well as convenient, flat, exhaustive pattern matching, which might be worth doing if we measured these as bottlenecks or considered the pattern matching thing to be sufficiently problematic. (I kinda don’t think it is, at the moment, but more experience will be helpful.)

**Comment by patrickt** [comment]
I think we can close this for now; in practice the `Prj` constraint synonym has been enormously helpful.
