### ISSUE TITLE
Unify tree-sitter’s `toDescription` and tree-sitter-python’s `escapeOperatorPunctuation`

### ISSUE THREAD

**Issue by patrickt** [tree-sitter/haskell-tree-sitter#159]
This is a lot of duplicated code.

**Comment by aymannadeem** [comment]
Word. I think they were both called `toDescription` before your recent [rename](https://github.com/tree-sitter/haskell-tree-sitter/commit/81b6ca32509ddbb2c62a3909c5dd6ea34606300b). I'll change the other `toDescription` too.
