### ISSUE TITLE
Rename `isNamed` field in `Datatype`.

### ISSUE THREAD

**Issue by patrickt** [tree-sitter/haskell-tree-sitter#165]
Our convention is to prefix with type names, so this should be `datatypeNameStatus` or `datatypeNomenclature` or something.

**Comment by aymannadeem** [comment]
`isNamed :: Named` is a field of `MkType`, did you mean that or the `isName` in `Datatype`? Just asking for this clarification has me doubly agreeing with renames tho.

**Comment by patrickt** [comment]
Both, I think!

**Comment by aymannadeem** [comment]
I renamed the one in `Datatype` but left `isNamed` in `MkType` because we derive the `Type` instance via Aeson's `customOptions`, which drop the prefix and match against the `"named"` key in the `node-types.json` file. 

I can change that whole instance if you feel strongly about renaming though.
