### ISSUE TITLE
Rename `toName` and pass it a `Type` rather than a `String, DatatypeName`

### ISSUE THREAD

**Issue by patrickt** [tree-sitter/haskell-tree-sitter#166]
`Type` holds both the data that we pass to `toName`. Cleaning this up will simplify a lot of code, and it gives us the opportunity to rename it to something else, like `thNameForType`.

**Comment by aymannadeem** [comment]
Need some clarity here, are you talking about consolidating 

```
datatypeName       :: DatatypeName
datatypeNameStatus :: Named
```

into `thNameForType :: Type`?

**Comment by patrickt** [comment]
While we _could_ consolidate those structures, I wouldn’t, since it makes the JSON decoding more fiddly. I would just change

```haskell
toName :: Named -> String -> Name
```

to

```haskell
toName :: Type -> Name
```

and then rename `toName` something to indicate both its inputs and outputs (like `typeInfoToTHName` or something).

**Comment by aymannadeem** [comment]
I brought up with @patrickt that `Type`s are only available for product and sum types, but not leaves. Existing approach is likely best.

**Comment by robrix** [comment]
> I brought up with @patrickt that `Type`s are only available for product and sum types, but not leaves. Existing approach is likely best.

The `Type`s available for product/sum types refer to their contents, not the type _of_ the sum/product type. So in all three cases (products, sums, and leaves) we’d want to instead convert the `Datatype` to a `Type` using its `DatatypeName` and `Named` fields.

**Comment by aymannadeem** [comment]
Oh yeah, you're right. But agreed, not sure if it adds any more convenience.
