### ISSUE TITLE
Improve codegen tests

### ISSUE THREAD

**Issue by aymannadeem** [tree-sitter/haskell-tree-sitter#180]
We only test very simple source inputs (ex., `pass` and `1`). Adding code examples that reflect complete examples of structures we generate would allow us to better validate correctness.

**Comment by robrix** [comment]
Likewise, it might be nice to combine the two test components into one so we can see all test failures more easily.

That might warrant migrating the `test` component from `hspec` to `tasty`, which I’d personally be ok with (especially since there’s so few tests in `test/Spec.hs`).
