### ISSUE TITLE
Add incomplete tree-sitter-c-sharp package

### ISSUE THREAD

**Issue by Benjamin-Davies** [tree-sitter/haskell-tree-sitter#185]
Add bindings for [tree-sitter-c-sharp](https://github.com/tree-sitter/tree-sitter-c-sharp).

Even though it is incomplete, partial support is better than none (IMHO). Also, it is my understanding that it is easy to update bindings if the base package changes, because of the way that this project is structured.

C# is a very popular language, and I would love to see it supported in the tools that depend on this library. I am particularly excited for `semantic`, ([link to C# issue on that repo](https://github.com/github/semantic/issues/156)) as it is likely to become the base of [GitHub's Code Navigation](https://help.github.com/en/articles/navigating-code-on-github).

**Comment by robrix** [comment]
Good call 👍

**Comment by damieng** [comment]
C# support is now quite complete, putting a PR together now.

**Comment by patrickt** [comment]
@damieng Awesome! Next step (sorry for telling you these things piecemeal; we’re currently fixing the docs!) is to add a `semantic-c-sharp` package in https://github.com/github/semantic, implement the required `ToTags` instances, integrate C# support into the CLI, and write some tests. Then the way forward for C# will be cleared technologically: our schedules and behind-the-scenes operational concerns will determine when support will land. Thank you so much for all your hard work!
