### ISSUE TITLE
Derive Data instances for AST nodes

### ISSUE THREAD

**Issue by patrickt** [tree-sitter/haskell-tree-sitter#186]
I want to use [uniplate](http://hackage.haskell.org/package/uniplate-1.6.12/docs/Data-Generics-Uniplate-Operations.html) for generic operations over syntax trees (a la recursion schemes). Though the fastest option would be to derive `Direct` instances for these operations, that would be a lot of tedious TH, so the easiest thing would be to derive an instance of `Data` [here](https://github.com/tree-sitter/haskell-tree-sitter/blob/master/tree-sitter/src/TreeSitter/GenerateSyntax.hs#L68).

**Comment by robrix** [comment]
@patrickt: How urgent/valuable is this for your current work? Should we increase the priority of this?
