### ISSUE TITLE
Typeclass for extracting annotations from ASTs

### ISSUE THREAD

**Issue by robrix** [tree-sitter/haskell-tree-sitter#208]
All AST nodes have annotations, but in sums it’s hidden away underneath the various constructors. It’d often be handy to be able to ask any arbitrary node for its annotation without having to worry about whether it’s a sum or a product.

We could accomplish that with a typeclass method, e.g. `annotation :: t a -> a`, which for leaves/products would simply return the value of the `ann` field, but for sums would distribute over the constructors instead.

**Comment by robrix** [comment]
Alternatively, instead of providing our own class for this, we could define `HasField` instances for sum types instead; they’re already a uniform way of accessing records, so this would simply extend them to sums as well.

**Comment by robrix** [comment]
We also occasionally need something like this for anonymous sums.

**Comment by patrickt** [comment]
I think this is taken care of by `HasField`, as well as appropriate use of `generic-lens`.
