### ISSUE TITLE
undefined reference to ‘tree_sitter_haskell’ during build

### ISSUE THREAD

**Issue by clojj** [tree-sitter/haskell-tree-sitter#70]
I think the question is how to build /vendor/tree-sitter libraries ?

Error message from stack build in the projects root directory is:

Linking .stack-work/dist/x86_64-linux-tinfo6/Cabal-2.0.1.0/build/test-parser/test-parser ...
.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.0.1.0/build/test-parser/test-parser-tmp/Main.o:Main_main1_info: error: undefined reference to 'tree_sitter_haskell'
collect2: error: ld returned 1 exit status
`gcc' failed in phase `Linker'. (Exit code: 1)

**Comment by patrickt** [comment]
@clojj Have you run `script/bootstrap`? That should take care of pulling the submodules, which may be your issue. You will also need `stack` rather than just `cabal` or `cabal new-build`.

**Comment by patrickt** [comment]
I will add a note on `script/bootstrap` to the docs. Changing the name of this bug until we can verify that `undefined reference to ‘tree_sitter_haskell’` is a bug from lack of script/bootstrap.

**Comment by clojj** [comment]
...trying to translate this to haskell:
https://tree-sitter.github.io/tree-sitter/using-parsers#an-example-program

**Comment by patrickt** [comment]
Wonderful. I’m closing this issue; please get in touch if you have further questions.
