### ISSUE TITLE
Usage example needed

### ISSUE THREAD

**Issue by clojj** [tree-sitter/haskell-tree-sitter#72]
https://tree-sitter.github.io/tree-sitter/using-parsers#editing

How to do this with this haskell binding is not obvious.
It would be great to have a Haskell example, showing how to use this binding:
1 parse and get the tree of nodes
2 edit and reparse

Also....
ts_node_edit and other API functions are not yet in the FFI binding.... not needed ?
or is a pull request welcome ?

**Comment by patrickt** [comment]
Hi @clojj! Thanks for pointing this out. 

Let me start by saying our that use case for this library is currently oriented towards running tree-sitter once, then converting the resulting parse tree into a higher-level data structure. This is quite different from the the parse->edit->reparse pipeline that you’ve pointed to, which is more like what Atom does. This is why we haven’t implemented `ts_node_edit` yet—we just haven’t needed it. A pull request to add the FFI call would not be unwelcome, should you need it.

I’ll try to write a more illustrative example this week. Hopefully someday we can OSS our libraries for converting from tree-sitter to a higher-level representation.

**Comment by clojj** [comment]
ok, I have pushed an example
https://github.com/clojj/hs-tree-sitter-test/blob/master/app/Main.hs

In the long run, I'd like to parse->edit->reparse. So I will give extending the FFI a shot at some point.
For now, I think I'll just do some work on that higher-level data structure.
`data Tree a = Node {rootLabel :: a, subForest :: Forest a}`
...that should do it I think

here's my example
![test](https://user-images.githubusercontent.com/4367963/47971080-eca44800-e08d-11e8-82e1-85624f6bc2d2.png)

**Comment by clojj** [comment]
If you'd like to pull my example (or have a better one yourself), it would be sure helpful for people in understanding this repo's intent

**Comment by patrickt** [comment]
@clojj This is awesome. Do you mind if I link this in the README? Feel free to iterate on the example, of course, especially since it sounds like you’ll be extending the FFI. Thank you so much for putting this together!

**Comment by clojj** [comment]
Sure!

**Comment by patrickt** [comment]
@clojj Great! I’ve linked to you in the README. Thank you so much! I’ll close this PR out; ping me if you have more ideas as to usage examples.
