### ISSUE TITLE
Bridging assertions are unrecoverable

### ISSUE THREAD

**Issue by robrix** [tree-sitter/haskell-tree-sitter#89]
> If we hit this assert, the calling Haskell program will die with what I believe is an unrecoverable exception. That might be okay for this case; what do you think? If necessary, we can wrap this in a function that throws some recoverable exception based on a return code.

_Originally posted by @patrickt in https://github.com/tree-sitter/haskell-tree-sitter/pull/87_

We’re basically just double-checking the `tree-sitter` inputs/outputs in a way that pin-points the bridged API responsible (and AFAIK none of these have tripped in years!), but we should probably do something smarter like @patrickt suggests.

**Comment by maxbrunsfeld** [comment]
To me, a plain `assert` (or just no check at all) seems ok here, since this is a condition that should never hit, if our code is correct.

I think runtime exceptions make more sense for external error conditions that we might want to detect and recover from programmatically.

**Comment by robrix** [comment]
Seems reasonable to me. @patrickt: Feel free to reopen if you disagree!
