### ISSUE TITLE
Leaf datatypes don’t have contents

### ISSUE THREAD

**Issue by robrix** [tree-sitter/haskell-tree-sitter#93]
Leaf datatypes currently have a single constructor with no fields, which means we have no way to distinguish between numbers `1` and `2`, or between identifiers `foo` and `bar` when using the datatypes. They should have a field for the textual contents of the node.

Incidentally, this means that they’ll be the right shape to be `newtype`s instead of `data` types!

re: @aymannadeem’s TH work in #86

**Comment by robrix** [comment]
As a fun special case (hooray!), _anonymous_ leaf datatypes should probably not have contents: the textual contents of `AnonymousPlus` will _always_ be `+`, so there’s no point in having a field for it.

I’m not actually sure how easy these are to distinguish, so we may end up wanting to add a `Text` field to all leaf nodes and figure out this part later on.

**Comment by aymannadeem** [comment]
Fixed by https://github.com/tree-sitter/haskell-tree-sitter/pull/86
