### ISSUE TITLE
AST datatypes don’t have annotations for source ranges/spans

### ISSUE THREAD

**Issue by robrix** [tree-sitter/haskell-tree-sitter#94]
We’re often going to want to have byte range/line & col span information associated with nodes, but currently the TH-generated datatypes don’t have any place to hold these.

**Comment by robrix** [comment]
Since we may want to associate other data with these nodes, I think we should make the annotations polymorphic—i.e. a type parameter instead of the range/span values per se.

**Comment by robrix** [comment]
Additionally, it’s worth noting that we’ll only have to add the annotation fields to leaf and product datatypes, not to sum datatypes: generated sum datatypes always contain exactly one child, so they can get their annotations from the child no matter which constructor is used.

i.e. we’d end up with datatypes something like so:

```haskell
-- sum
data Expr a
  = IdentExpr (Ident a)
  | BinOpExpr (BinOp a)

-- leaf
data Ident a = Ident { ann :: a, content :: Text }

-- product
data BinOp a = BinOp { ann :: a, left :: Expr, op :: Either (AnonPlus a) (AnonTimes a), right :: Expr}

-- anonymous leaves
data AnonPlus a = AnonPlus { ann :: a }
data AnonTimes a = AnonTimes { ann :: a }
```

(Note that this also has the fields from #93.)

**Comment by patrickt** [comment]
I’m not convinced that adding a new type parameter is the right thing here. Under what circumstances are we going to store anything other than a `Location` parsed from tree-sitter?

**Comment by robrix** [comment]
@patrickt: fair; functors are pretty useful for general syntax manipulation, plus it _should_ be easy to unmarshal with only a `Range`, or only a `Span`, or neither, but maybe it’s not such a pressing concern.

**Comment by robrix** [comment]
Counterpoint: annotation-agnostic equality is important for diffing. We currently do `(() <$ a) == (() <$ b)` which is extremely convenient.
