### ISSUE TITLE
Shall we generate code or use splices directly?

### ISSUE THREAD

**Issue by patrickt** [tree-sitter/haskell-tree-sitter#98]
As per discussion in #91 and elsewhere, we have a choice to make: when generating data types from a `node-types.json` file, should this generation be performed as a native Template Haskell splice (i.e. `’dataTypesForConstructors …` in a file), or should it generate a whole `.hs` file? 

Some advantages of code generation:
• Possibly less surprising—most people don’t expect invoking a Template Haskell splice to do disk I/O (I don’t, at least)
• Bugs or infinite loops would show up at codegen rather than compile time
• Better build cache artifact behavior, especially for these very large files

We don’t have to commit to one or the other now, just raising this as something to think about.

**Comment by robrix** [comment]
IMO, this issue is still relevant.

**Comment by robrix** [comment]
One thing that would be convenient about this is that we could update the language packages independently from the codegen code. This would also mean that we could avoid having to bump the lower bound on the `tree-sitter` dependency in (e.g.) `tree-sitter-python` every time we ship codegen changes in `tree-sitter`, as long as the generated code would still unmarshal.

**Comment by robrix** [comment]
One challenge: continuing to support customizing some of the generated datatypes would become a little bit trickier since we wouldn’t expect the datatypes in question to exist in the same module. We can work around this, however.

**Comment by patrickt** [comment]
Generating code directly would enable us to sidestep https://github.com/haskell/cabal/issues/6412.

**Comment by robrix** [comment]
Unfortunately, this doesn’t really work, since it requires that we have run the code in `IO`, and `IO`’s `Quasi` instance doesn’t (even _can’t_) do some things. Thus, the code we get as a result won’t compile, because e.g. names are wrong.

Sadly, it seems that `-ddump-splices` isn’t any better where this is concerned—the splices are dumped before some of the work has been done, and so we get broken code that nevertheless works just fine when splicing the declarations instead.

**Comment by patrickt** [comment]
I think we’ve settled on using splices rather than generating code directly, since we’ve reorganized the project in such a way that it is less ruinous time-wise.
